# Standards: 0.11
---

- include: facts/date_time_pid.yml
  tags:
    - level-1
    - section-1
    - "2.1.8"
    - scored

- name: 2.1.8 - Check if telnet is installed
  yum:
    list: telnet-server
  register: telnet_package_status
  tags:
    - level-1
    - "2.1.8"
    - scored

- name: 2.1.8 Ensure telnet server is not enabled (Scored)
  command: chkconfig --list telnet
  register: which_2_1_8
  ignore_errors: True
  changed_when: False
  when: telnet_package_status | selectattr("yumstate", "match", "installed") | list | length != '0'
  tags:
    - level-1
    - "2.1.8"
    - scored

- name: 2.1.8 - Display registered output
  debug:
    msg: Ouput message is {{ which_2_1_8 }}
  when: which_2_1_8 is defined
  tags:
    - level-1
    - "2.1.8"
    - scored

- name: 2.1.8 - Ensure telnet service is disabled
  service:
    name: telnet
    state: stopped
    enabled: False
  when: 
    - which_2_1_8 is defined and 'on' in which_2_1_8
    - telnet_package_status | selectattr("yumstate", "match", "installed") | list | length != '0'
  register: action_2_1_8_01

  tags:
    - level-1
    - "2.1.8"
    - scored

- name: 2.1.8 - Logging action systemctl disable telnet.socket
  lineinfile:
    path: "{{ cis_hot_fix_ansible_log }}"
    create: yes
    line: "{{ date_time }} : {{ process_id }}: 2.1.8 : Execute 'chkconfig off telnet'"
  when: action_2_1_8_01 is defined and action_2_1_8_01.changed  
  tags:
    - level-1
    - "2.1.8"
    - scored