# Standards: 0.11
---

- include: facts/date_time_pid.yml
  tags:
    - level-1
    - section-1
    - "2.1.8"
    - scored

- name: 2.1.8 - Ensure telnet service is disabled
  service:
    name: telnet
    state: stopped
    enabled: False
  when: service_status_2_1_8 is defined and 'on' in service_status_2_1_8.stdout_lines
  register: action_2_1_8_01

  tags:
    - level-1
    - "2.1.8"
    - scored

- name: 2.1.8 - Logging action 'chkconfig telnet off'
  lineinfile:
    path: "{{ cis_hot_fix_ansible_log }}"
    create: yes
    line: "{{ date_time }} : {{ process_id }}: 2.1.8 : Execute 'chkconfig off telnet'"
  when: action_2_1_8_01 is defined and action_2_1_8_01.changed  
  tags:
    - level-1
    - "2.1.8"
    - scored