# Standards: 0.11
---

- include: facts/date_time_pid.yml
  tags:
    - level-1
    - section-1
    - "2.1.8"
    - scored

- name: 2.1.8 - Check if telnet is installed
  yum:
    list: telnet-server
  register: telnet_package_status
  tags:
    - level-1
    - "2.1.8"
    - scored

- name: 2.1.8 - Check if telnet-server service status
  command: chkconfig --list telnet
  register: service_status_2_1_8
  ignore_errors: True
  changed_when: False
  tags:
    - level-1
    - "2.1.8"
    - scored

- name: 2.1.8 - Display telnet-server status
  debug:
    msg: "Ouput message telnet-server is enabled"
  when: service_status_2_1_8 is defined and 'on' in service_status_2_1_8.stdout_lines
  tags:
    - level-1
    - "2.1.8"
    - scored

- name: 2.1.8 - Ensure telnet service is disabled
  service:
    name: telnet
    state: stopped
    enabled: False
  when: service_status_2_1_8 is defined and 'on' in service_status_2_1_8.stdout_lines
  register: action_2_1_8_01

  tags:
    - level-1
    - "2.1.8"
    - scored

- name: 2.1.8 - Logging action systemctl disable telnet.socket
  lineinfile:
    path: "{{ cis_hot_fix_ansible_log }}"
    create: yes
    line: "{{ date_time }} : {{ process_id }}: 2.1.8 : Execute 'chkconfig off telnet'"
  when: action_2_1_8_01 is defined and action_2_1_8_01.changed  
  tags:
    - level-1
    - "2.1.8"
    - scored